"""Private, atomic recovery records; credentials are never stored in job records."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any
from uuid import UUID

from duhui_config import resolve_config_path


def job_path(job_id: str) -> Path:
    if str(UUID(job_id)) != job_id:
        raise ValueError("Invalid recovery job ID")
    return resolve_config_path().parent / "jobs" / f"{job_id}.json"


def save_job(job_id: str, record: dict[str, Any]) -> None:
    path = job_path(job_id)
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    fd, name = tempfile.mkstemp(prefix=".job-", dir=path.parent)
    temporary = Path(name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            if hasattr(os, "fchmod"):
                os.fchmod(stream.fileno(), 0o600)
            json.dump(record, stream, ensure_ascii=False)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def load_job(job_id: str) -> dict[str, Any]:
    record = json.loads(job_path(job_id).read_text(encoding="utf-8"))
    if not isinstance(record, dict) or record.get("schema_version") != 1:
        raise ValueError("Invalid recovery record")
    for key in ("input_path", "input_format", "output_format", "output_path", "object_key", "phase"):
        if not isinstance(record.get(key), str):
            raise ValueError("Incomplete recovery record")
    if not isinstance(record.get("options"), dict):
        raise ValueError("Invalid recovery options")
    if not isinstance(record.get("explicit_output"), bool):
        raise ValueError("Invalid recovery output target")
    # Only object names generated by this skill may be deleted during recovery.
    object_key = record["object_key"]
    if not object_key.startswith("up/") or "/" in object_key[3:]:
        raise ValueError("Invalid recovery source object")
    UUID(object_key[3:].split(".", 1)[0])
    return record


def list_jobs() -> list[dict[str, str]]:
    directory = resolve_config_path().parent / "jobs"
    return [{"job_id": path.stem, "phase": load_job(path.stem)["phase"]}
            for path in sorted(directory.glob("*.json"))]


def remove_job(job_id: str) -> None:
    job_path(job_id).unlink(missing_ok=True)
